title: "Its Just Joe"
description: "Clash Royale news, meta snapshots, decks, and videos."

# ✅ For a project site, use domain in `url` and the repo path in `baseurl`
url: "https://jrm328.github.io"
baseurl: "/link-in-bio"

permalink: /:categories/:title/

theme: null
remote_theme: "mmistakes/minimal-mistakes@latest"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

minimal_mistakes_skin: "dark"
# (Optional) pagination works best on the homepage with layout: home
# Disable for now to avoid warnings; re-enable later if you paginate the home page.
paginate: 0
paginate_path: /news/page:num/

search: true
lunr:
  search_within_pages: true

collections:
  videos:  { output: true, permalink: /videos/:name/ }
  decks:   { output: true, permalink: /decks/:name/ }
  patches: { output: true, permalink: /patches/:name/ }

defaults:
  - scope: { path: "", type: "posts" }
    values: { layout: single, author_profile: true, read_time: true, share: true, related: true }
  - scope: { path: "", type: "videos" }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: "decks" }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: "patches" }
    values: { layout: single, author_profile: true }

author:
  name: "Joe"
  avatar: "{{ '/assets/img/avatar.png' | relative_url }}"
  bio: "Clash Royale news, meta & decks—plus weekly videos."
  links:
    - label: YouTube
      icon: "fab fa-youtube"
      url: "https://youtube.com/@itsjustjoecr"
    - label: X / Twitter
      icon: "fab fa-twitter"
      url: "https://x.com/"
    - label: Contact
      icon: "fas fa-envelope"
      url: "{{ '/contact/' | relative_url }}"

social:
  name: "Its Just Joe"
  links:
    - https://youtube.com/@itsjustjoecr
    - https://x.com/
feed:
  path: feed.xml

jekyll-archives:
  enabled: [categories, tags]
  layouts: { category: archive-taxonomy, tag: archive-taxonomy }
  permalinks: { category: /category/:name/, tag: /tag/:name/ }
